# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["develop"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    defaults:
      run:
        shell: bash
        working-directory: .
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup for GitHub Pages
        uses: actions/configure-pages@v5
      
      - name: Copy files to their web-ready locations
        run: ./setuppages.sh
      
      - name: Insall minify tool
        run: apt install minify

      # Work around for Gulp CSS-Concat being unmaintained
      # Relies on work done in setuppages.sh
      - name: Copy minified CSS to /docs/css/app-toolkit.css
        run: ./setup_bundles.sh

      - run: npm install
      - run: npm rebuild
      - name: Run Gulp script to minify JS and copy images
        run: npm run-script build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:       
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
